#ddev-generated
# If you remove the ddev-generated line above you
# are responsible for maintaining this file. DDEV will not then
# update it, for example if you add `additional_hostnames`, etc.

http:
  routers:
    teko-software-engineering-parkhaus-software-xhgui-80-http:
      entrypoints:
        - http-8143
      rule: HostRegexp(`^teko-software-engineering-parkhaus-software\.ddev\.site$`)
      
      service: "teko-software-engineering-parkhaus-software-xhgui-80"
      tls: false
      # middlewares:
      #   - "teko-software-engineering-parkhaus-software-redirectHttps"
    teko-software-engineering-parkhaus-software-web-80-http:
      entrypoints:
        - http-80
      rule: HostRegexp(`^teko-software-engineering-parkhaus-software\.ddev\.site$`)
      
      service: "teko-software-engineering-parkhaus-software-web-80"
      tls: false
      # middlewares:
      #   - "teko-software-engineering-parkhaus-software-redirectHttps"
    teko-software-engineering-parkhaus-software-web-8025-http:
      entrypoints:
        - http-8025
      rule: HostRegexp(`^teko-software-engineering-parkhaus-software\.ddev\.site$`)
      
      service: "teko-software-engineering-parkhaus-software-web-8025"
      tls: false
      # middlewares:
      #   - "teko-software-engineering-parkhaus-software-redirectHttps"
    
    
    teko-software-engineering-parkhaus-software-xhgui-80-https:
      entrypoints:
        - http-8142
      rule: HostRegexp(`^teko-software-engineering-parkhaus-software\.ddev\.site$`)
      
      service: "teko-software-engineering-parkhaus-software-xhgui-80"
      
      tls: true
      
    
    
    teko-software-engineering-parkhaus-software-web-80-https:
      entrypoints:
        - http-443
      rule: HostRegexp(`^teko-software-engineering-parkhaus-software\.ddev\.site$`)
      
      service: "teko-software-engineering-parkhaus-software-web-80"
      
      tls: true
      
    teko-software-engineering-parkhaus-software-web-8025-https:
      entrypoints:
        - http-8026
      rule: HostRegexp(`^teko-software-engineering-parkhaus-software\.ddev\.site$`)
      
      service: "teko-software-engineering-parkhaus-software-web-8025"
      
      tls: true
      
    

  middlewares:
    teko-software-engineering-parkhaus-software-redirectHttps:
      redirectScheme:
        scheme: https
        permanent: true

  services:
    teko-software-engineering-parkhaus-software-xhgui-80:
      loadbalancer:
        servers:
          - url: http://ddev-teko-software-engineering-parkhaus-software-xhgui:80
        
    
    teko-software-engineering-parkhaus-software-web-80:
      loadbalancer:
        servers:
          - url: http://ddev-teko-software-engineering-parkhaus-software-web:80
        
    teko-software-engineering-parkhaus-software-web-8025:
      loadbalancer:
        servers:
          - url: http://ddev-teko-software-engineering-parkhaus-software-web:8025
        
    
    
    

tls:
  certificates:
    - certFile: /mnt/ddev-global-cache/traefik/certs/teko-software-engineering-parkhaus-software.crt
      keyFile: /mnt/ddev-global-cache/traefik/certs/teko-software-engineering-parkhaus-software.key